In [2]:
import requests
import pandas as pd

url = "https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page=1&sort_by=popularity.desc"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI4ZjcyOGJjNGFkNGFmZTRhNzBiMmQ4YWY1YmQyZDZkOCIsIm5iZiI6MTc4Mzc1Nzg0My4xMDQsInN1YiI6IjZhNTFmYzEzY2IzM2RmMjdkMjA1MzMxMSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.pO9ssnu1XmDG2Sxg4-Allxt1InmrOkDxV_32anOeXAk"
}

response = requests.get(url, headers=headers)


#response.json()
# Converting into Dataframe
df = pd.DataFrame(response.json()['results'])
df

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/7iwUUcKURMT7aKfCwMy6YnGtchD.jpg,"[878, 28, 12]",969681,Spider-Man: Brand New Day,en,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,952.5320,/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg,2026-07-29,False,False,7.900,2347
1,False,/RMXG8myu1aGlNUsRjtxzmpdMK0.jpg,"[12, 28, 14]",1368337,The Odyssey,en,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",544.3226,/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg,2026-07-15,False,False,7.991,3398
2,False,/qDa0fqDqIBCovRp975RvtGPcuN3.jpg,"[28, 53]",1288445,Mutiny,en,Mutiny,After witnessing his billionaire boss' murder ...,412.2288,/pu2VxGlpGwffOx292w18b1tv96j.jpg,2026-08-19,False,False,6.300,255
3,False,/zFCWfU2ViMIm38G1W8UsnSpqmWn.jpg,"[10749, 18]",1516698,The Last Sunrise,en,The Last Sunrise,"Ry, a college student with a chronic illness, ...",318.6222,/3PWJqDfygN0YNNjWsDUOXclCp3h.jpg,2026-08-26,False,False,6.600,90
4,False,/c4U96GrPRfnNrS01mBtqnocvlLJ.jpg,"[80, 28, 53]",1621552,Facing El Chapo,es,La captura,Two Mexican officers must survive the final ho...,275.7130,/z8eF0ACFFKtIZ4pUeo02PCzxRVO.jpg,2026-08-21,False,False,8.864,452
5,False,/tBRSSfgqOAq7YlG8udcoJIBm2FG.jpg,"[28, 80, 18]",1213243,Toxic: A Fairy Tale for Grown-ups,kn,ಟಾಕ್ಸಿಕ್,A powerful drug cartel pulls the strings behin...,260.8412,/oiIPU4lvnI0Ag2K9cyAi44eCaoE.jpg,2026-08-26,False,False,7.500,46
6,False,/viZqGq9TNvQ5uXSD4ahg2RpRONT.jpg,"[35, 12, 10751]",1204680,Coyote vs. Acme,en,Coyote vs. Acme,After Acme products fail him one too many time...,246.8996,/vhv7lBWYM0DUuNU2a0V7Rhq21dD.jpg,2026-08-20,False,False,7.900,74
7,False,/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg,"[27, 53]",1339713,Obsession,en,Obsession,"After breaking the mysterious ""One Wish Willow...",218.7101,/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg,2026-05-13,False,False,8.205,5236
8,False,/dNKFETDDujxm2PUN873Jwiw5VML.jpg,"[27, 14, 9648]",1232569,Pinocchio: Unstrung,en,Pinocchio: Unstrung,Influenced by a sinister Cricket and created b...,230.3675,/eUJXk3bTvLBi5Zcb0BCedZU7lVL.jpg,2026-07-22,False,False,6.700,72
9,False,/yjK3ardrgdS8suZG8KMU82Q7U38.jpg,[10749],1285366,Shape of My Heart,ja,愛のぬくもり,"A romance about a man and a woman who, due to ...",270.7527,/3r0O6BW9USoZ9mteCVyNKMQriRL.jpg,2024-07-06,False,False,5.200,5
10,False,/xSJJQeAp9GBFmiKusysTRG6jQjt.jpg,"[80, 18, 53]",860508,The Whisper Man,en,The Whisper Man,"When his young son vanishes, a widower enlists...",233.5012,/6UqflU8Qqkz7Dq4swJPqs0ZJjY4.jpg,2026-08-27,False,False,6.400,262
11,False,/z7lZgL5tzefTfhyRtouThFhsuUS.jpg,"[28, 878, 53]",1323244,Rage of Stars,en,Rage of Stars,A story about a woman from the International S...,198.3525,/oLld47ZT1I3iecM3OWhIphohQUJ.jpg,2026-08-06,False,False,5.554,56
12,False,/8sSKdEmlmqF4kJUd28SqthXC4yZ.jpg,"[16, 10751, 35, 12]",1084244,Toy Story 5,en,Toy Story 5,When Bonnie receives a Lilypad tablet as a gif...,205.1440,/sfQtVlIHljToOwYjhe21KPGzZWK.jpg,2026-06-17,False,False,8.313,1887
13,False,/hpBGCnzOvdtQoMyE48gvwp2y5yx.jpg,"[28, 27, 878]",1375646,Colony,ko,군체,Professor Se-jeong is thrust into a bloody nig...,177.3214,/tN799oUR0f1gUKDYdMNrDaY7I51.jpg,2026-05-21,False,False,8.100,665
14,False,/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg,"[10751, 14, 35, 12]",1108427,Moana,en,Moana,"Teenage Moana answers the Ocean's call and, fo...",174.0445,/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg,2026-07-08,False,False,6.139,251
15,False,/kkcwhgSFd81QDlXo8ytrpHPQjhy.jpg,"[12, 16, 35, 10751, 14]",1315772,Minions & Monsters,en,Minions & Monsters,"This is the rambunctious, ridiculous and total...",183.0322,/4LwvU9SZc8QQzW1X1FAPhNbXnEU.jpg,2026-06-24,False,False,7.593,973
16,False,/caBIySpwuFi2i7ynvHIlnxJLOdN.jpg,"[16, 28, 12, 878, 80, 18]",1560520,Batman: Knightfall Part 1: Knightfall,en,Batman: Knightfall Part 1: Knightfall,"Arkham Asylum has been destroyed, and all its ...",164.7150,/360qdtu2hLnqMu8SVHMywn420w1.jpg,2026-06-23,False,False,9.000,159
17,False,/tK3QdOOrX4qEkmSlvrmc8cK7iOU.jpg,"[27, 35, 53]",1393326,Ghost in the Cell,id,Hantu Dalam Sel,"In a notorious prison, an invisible force begi...",159.9308,/zxcMdx0w5Zmg8yZuuiS7CJ8vOea.jpg,2026-04-16,False,False,7.100,39
18,False,/lSd6nEnlaeQkswLLUgHC5gyuXyU.jpg,"[28, 53, 27, 80]",1514682,Above & Below,en,Above & Below,A group of friends set off for an unforgettabl...,148.3248,/7bOuu1SRALGwsG2fLCTvRkCmQBj.jpg,2026-07-29,False,False,6.545,11
19,False,/uyrOU4BDm2kbVxFsMiDFIHDhc4d.jpg,"[28, 12, 878]",634649,Spider-Man: No Way Home,en,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,131.4164,/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg,2021-12-15,False,False,7.945,22967

In [3]:
# Extracting required Info

df = df.head(10)[['id', 'title', 'overview', 'popularity', 'release_date', 'vote_average', 'vote_count']]
df

,id,title,overview,popularity,release_date,vote_average,vote_count
0,969681,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,952.5320,2026-07-29,7.900,2347
1,1368337,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",544.3226,2026-07-15,7.991,3398
2,1288445,Mutiny,After witnessing his billionaire boss' murder ...,412.2288,2026-08-19,6.300,255
3,1516698,The Last Sunrise,"Ry, a college student with a chronic illness, ...",318.6222,2026-08-26,6.600,90
4,1621552,Facing El Chapo,Two Mexican officers must survive the final ho...,275.7130,2026-08-21,8.864,452
5,1213243,Toxic: A Fairy Tale for Grown-ups,A powerful drug cartel pulls the strings behin...,260.8412,2026-08-26,7.500,46
6,1204680,Coyote vs. Acme,After Acme products fail him one too many time...,246.8996,2026-08-20,7.900,74
7,1339713,Obsession,"After breaking the mysterious ""One Wish Willow...",218.7101,2026-05-13,8.205,5236
8,1232569,Pinocchio: Unstrung,Influenced by a sinister Cricket and created b...,230.3675,2026-07-22,6.700,72
9,1285366,Shape of My Heart,"A romance about a man and a woman who, due to ...",270.7527,2024-07-06,5.200,5